#!/bin/zsh

JUST_BUILD=false
BUILD_CONFIG="Debug"

# Parse arguments
for arg in "$@"; do
    case $arg in
        build)
            JUST_BUILD=true
            ;;
        release)
            BUILD_CONFIG="Release"
            ;;
        debug)
            BUILD_CONFIG="Debug"
            ;;
    esac
done

echo "Build configuration: $BUILD_CONFIG"

# Generate BuildInfo.swift with dependency versions
echo "Generating BuildInfo.swift..."
BUILDINFO_PATH="OpenSuperWhisper/BuildInfo.swift"

# Extract versions
WHISPER_VERSION=$(cd libwhisper/whisper.cpp && git describe --tags 2>/dev/null || git rev-parse --short HEAD)
PACKAGE_RESOLVED="OpenSuperWhisper.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved"
GRDB_VERSION=$(grep -A10 '"identity" : "grdb.swift"' "$PACKAGE_RESOLVED" | grep '"version"' | head -1 | sed 's/.*: "\([^"]*\)".*/\1/')
KEYBOARD_SHORTCUTS_VERSION=$(grep -A10 '"identity" : "keyboardshortcuts"' "$PACKAGE_RESOLVED" | grep '"version"' | head -1 | sed 's/.*: "\([^"]*\)".*/\1/')
AUTOCORRECT_VERSION=$(grep '^version' asian-autocorrect/autocorrect-swift/Cargo.toml | head -1 | sed 's/version = "\(.*\)"/\1/')
LIBOMP_VERSION=$(otool -L /opt/homebrew/opt/libomp/lib/libomp.dylib 2>/dev/null | grep "current version" | head -1 | sed 's/.*current version \([0-9.]*\).*/\1/' || echo "5.0.0")
BUILD_DATE=$(date +%Y-%m-%d)

cat > "$BUILDINFO_PATH" << EOF
// BuildInfo.swift - Auto-generated by run.sh, do not edit manually
import Foundation

struct BuildInfo {
    static let whisperCppVersion = "$WHISPER_VERSION"
    static let grdbVersion = "$GRDB_VERSION"
    static let keyboardShortcutsVersion = "$KEYBOARD_SHORTCUTS_VERSION"
    static let autocorrectVersion = "$AUTOCORRECT_VERSION"
    static let libompVersion = "$LIBOMP_VERSION"
    static let buildDate = "$BUILD_DATE"

    static let repositoryURL = URL(string: "https://github.com/happyjake/OpenSuperWhisper")!
    static let originalRepoURL = URL(string: "https://github.com/Starmel/OpenSuperWhisper")!
    static let whisperCppURL = URL(string: "https://github.com/ggerganov/whisper.cpp")!
    static let licenseURL = URL(string: "https://github.com/ggerganov/whisper.cpp/blob/master/LICENSE")!
}
EOF

echo "BuildInfo.swift generated with whisper.cpp $WHISPER_VERSION"

# Configure libwhisper
echo "Configuring libwhisper..."
cmake -G Xcode -B libwhisper/build -S libwhisper
if [[ $? -ne 0 ]]; then
    echo "CMake configuration failed!"
    exit 1
fi

echo "Building autocorrect-swift..."
mkdir -p build
cargo build -p autocorrect-swift --release --target aarch64-apple-darwin --manifest-path=asian-autocorrect/Cargo.toml
cp ./asian-autocorrect/target/aarch64-apple-darwin/release/libautocorrect_swift.dylib ./build/libautocorrect_swift.dylib
install_name_tool -id "@rpath/libautocorrect_swift.dylib" ./build/libautocorrect_swift.dylib
codesign --force --sign - ./build/libautocorrect_swift.dylib
if [[ $? -ne 0 ]]; then
    echo "Cargo build failed!"
    exit 1
fi

echo "Copying libomp.dylib..."
rm -f ./build/libomp.dylib 2>/dev/null
cp /opt/homebrew/opt/libomp/lib/libomp.dylib ./build/libomp.dylib
install_name_tool -id "@rpath/libomp.dylib" ./build/libomp.dylib
codesign --force --sign - ./build/libomp.dylib

# Build the app
echo "Building OpenSuperWhisper ($BUILD_CONFIG)..."
BUILD_OUTPUT=$(xcodebuild -scheme OpenSuperWhisper -configuration $BUILD_CONFIG -jobs 8 -derivedDataPath build -quiet -destination 'platform=macOS,arch=arm64' -skipPackagePluginValidation -skipMacroValidation -UseModernBuildSystem=YES -clonedSourcePackagesDirPath SourcePackages -skipUnavailableActions CODE_SIGNING_ALLOWED=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO build 2>&1)

# sudo gem install xcpretty
if command -v xcpretty &> /dev/null
then
    echo "$BUILD_OUTPUT" | xcpretty --simple --color
else
    echo "$BUILD_OUTPUT"
fi

# Check if build output contains BUILD FAILED or if the command failed
if [[ $? -eq 0 ]] && [[ ! "$BUILD_OUTPUT" =~ "BUILD FAILED" ]]; then
    APP_PATH="./Build/Build/Products/$BUILD_CONFIG/OpenSuperWhisper.app"
    echo "App built successfully!"

    # Ad-hoc sign the app bundle (required for Release builds to run)
    echo "Ad-hoc signing app bundle..."
    codesign --force --deep --sign - "$APP_PATH"

    echo "Location: $APP_PATH"
    if $JUST_BUILD; then
        exit 0
    fi
    echo "Starting the app..."
    # Remove quarantine attribute if exists
    xattr -d com.apple.quarantine "$APP_PATH" 2>/dev/null || true
    # Run the app and show logs
    "$APP_PATH/Contents/MacOS/OpenSuperWhisper"
else
    echo "Build failed!"
    exit 1
fi 